Viweb\SystemBundle\Entity\SectionTranslation:
    type: entity
    table: null
    repositoryClass: Viweb\SystemBundle\Repository\SectionTranslationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        slug:
            type: string
            length: 255
            unique: true
            nullable: true
    lifecycleCallbacks: {  }
