sylius_grid:
    templates:
        action:
            default: "@ViwebSystem/Grid/Action/default.html.twig"
            create: "@ViwebSystem/Grid/Action/create.html.twig"
            delete: "@ViwebSystem/Grid/Action/delete.html.twig"
            show: "@ViwebSystem/Grid/Action/show.html.twig"
            update: "@ViwebSystem/Grid/Action/update.html.twig"
            apply_transition: "@ViwebSystem/Grid/Action/applyTransition.html.twig"
            links: "@ViwebSystem/Grid/Action/links.html.twig"

        filter:
            string: "@ViwebSystem/Grid/Filter/string.html.twig"
            boolean: "@ViwebSystem/Grid/Filter/boolean.html.twig"
            date: "@ViwebSystem/Grid/Filter/date.html.twig"
            entity: "@ViwebSystem/Grid/Filter/entity.html.twig"
            money: "@ViwebSystem/Grid/Filter/money.html.twig"
    grids:
        viweb_section:
            driver:
                name: doctrine/orm
                options:
                    class: Viweb\SystemBundle\Entity\Section
            fields:
                name:
                    type: string
                    label: Name
                slug:
                    type: string
                    label: Slug
            actions:
                main:
                    create:
                        type: create
                        label: sylius.ui.create
                        icon: 'icon-external-link'
                        options: { }
                item:
                    update:
                        type: update
                        label: sylius.ui.edit
                        options: { }
                    delete:
                        type: delete
                        label: sylius.ui.delete
                        options: { }
