<?php

namespace Viweb\SystemBundle\Repository;

/**
 * BlockTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlockTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
