<?php

namespace Viweb\SystemBundle\Repository;

use Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository;

/**
 * SectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SectionRepository extends EntityRepository
{
    public function findOneByFullSlug($slug, $locale)
    {
        try {
            $qb = $this->createQueryBuilder('s');
            $qb->select('s', 'st')
                ->innerJoin('s.translations', 'st')
//                ->leftJoin('s.blocks', 'b')
//                ->leftJoin('b.translations', 'bt')
                ->andWhere('st.slug = :slug')
//                ->andWhere('bt.locale = :locale')
                ->andWhere('st.locale = :locale')
                ->setParameters(['locale' => $locale, 'slug' => $slug])
            ;
            return $qb->getQuery()->getSingleResult();

        } catch (\Exception $e) {

        }
    }

    public function findForMenuBuilder()
    {
        $qb = $this->createQueryBuilder('s');
        $qb->select('s', 'st')
            ->innerJoin('s.translations', 'st')
//                ->leftJoin('s.blocks', 'b')
//                ->leftJoin('b.translations', 'bt')
//            ->andWhere('st.slug = :slug')
//                ->andWhere('bt.locale = :locale')
//            ->andWhere('st.locale = :locale')
//            ->setParameters(['locale' => $locale, 'slug' => $slug])
        ;
        return $qb->getQuery()->getResults();
    }
}
