<?php

namespace Viweb\SystemBundle\Repository;

/**
 * SectionTransltionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SectionTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
